### ISSUE TITLE
missing import file

### ISSUE THREAD

**Issue by cerabinowitz** [des3pi/Public_Des3PI#1]
In des3pi_one_run.py there seems to be a missing file for `import clustering`, can the file be added to the repo?

**Comment by maxence92** [comment]
Dear cerabinowitz,

Thank you for your interest in our method.

There were probably an upload issue. The module clustering.py have just been added to the repo. We also updated the file des3pi_one_run.py, so please update the whole repository before trying again.

Please let us know if you need any help in the use of Des3PI.

Regards.

**Comment by cerabinowitz** [comment]
Thank you!

There also seems to be a missing directory called "aa_library", would you be able to upload that as well?

**Comment by maxence92** [comment]
Sure, it has been done.

Sorry for these upload problems.

I keep this discussion open until you are able to run the software.

Regards.

**Comment by cerabinowitz** [comment]
I am running into another error now.

```
Traceback (most recent call last):
  File "/home/Public_Des3PI/des3pi_one_run.py", line 65, in <module>
    compute_ca.compute_ca(start_dir,nb_dock)
  File "/home/Public_Des3PI/compute_ca.py", line 17, in compute_ca
    os.chdir(fragment_name)
FileNotFoundError: [Errno 2] No such file or directory: 'ile'
```

Is there just supposed to be a line above this that creates a directory `fragment_name`?

**Comment by maxence92** [comment]
The line that was suppose to create the fragment directory and run the docking of all the amino acids was muted to test part of the code.

I just fixed the muted line to make it work.

You just need to update the repository on your local machine

Tell me if everything is ok after this.

**Comment by cerabinowitz** [comment]
I am having some trouble installing vina - how did you install it to use it in run_simulation.py?

**Comment by maxence92** [comment]
As the installation of VINA was done a long time before my PhD position in the team, I just know that we are using AutoDock Vina 1.1.2 that you can download here https://vina.scripps.edu/downloads/. 
The program has to be installed on your Linux system. Des3PI calls VINA function using a bash command line. Make sure you are able to call "vina" on a linux terminal.

If you don't find a way to install VINA, I will check the way it is done on my computer in the beginning of next week (Tomorrow is a day-off in France, I don't have the access to the lab).

Regards

**Comment by thaduong** [comment]
Dear Cerabinowitz, 

To install Vina, please visit the web site https://vina.scripps.edu/downloads/ and follow the installation instruction. 
If you are on a Debian-based Linux, I think that you can also open a terminal and simply type the command : "sudo apt install vina" 

Best regards, 


	

	
Pr Tâp HA-DUONG 
BioCIS - UMR CNRS 8076 - Équipe FLUOPEPIT 
17 avenue des Sciences, 91400 ORSAY 
Bâtiment HM1 - 1er étage - Bureau 1804 
Tel : 01 80 00 63 76 



De: "cerabinowitz" ***@***.***> 
À: "des3pi/Public_Des3PI" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Envoyé: Jeudi 13 Juillet 2023 21:48:02 
Objet: Re: [des3pi/Public_Des3PI] missing import file (Issue #1) 





I am having some trouble installing vina - how did you install it to use it in run_simulation.py?

**Comment by cerabinowitz** [comment]
Thank you, I think I got it working.

I had to change the vina command to the path of the vina binary file.
